services:
  backend:
    build:
      context: ./backend
    container_name: backend-ippat
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "9056:9056"
    networks:
      - ippat-net
    depends_on:
      - mysql:
          condition: service_healthy 

  frontend:
    build:
      context: ./frontend
    container_name: frontend-ippat
    restart: always
    env_file:
      - ./frontend/.env.production
    ports:
      - "4050:4050"
    depends_on:
      - backend
    networks:
      - ippat-net

  mysql:
    image: mysql:8.0
    container_name: mysql-ippat
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: polinema
      MYSQL_DATABASE: ippat_db
      MYSQL_USER: ippat_user
      MYSQL_PASSWORD: polinema
    volumes:
      - mysql_data:/var/lib/mysql  
    networks:
      - ippat-net
    ports:
      - "3306:3306" 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

networks:
  ippat-net:
    driver: bridge

volumes:
  mysql_data:  