name: Deploy to VPS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          # Masuk ke direktori project
          cd skirpsi-ippat
          
          # Pull latest changes
          git pull origin main
          
          # Stop existing containers
          docker compose down
          
          # Remove old images (optional, untuk menghemat space)
          docker image prune -f
          
          # Build and start containers
          docker compose up -d --build
          
          # Show running containers
          docker ps
          
          # Show logs untuk debugging jika diperlukan
          echo "Deployment completed!"
          echo "Backend logs:"
          docker logs neon-backend --tail 20
          echo "Frontend logs:"
          docker logs neon-frontend --tail 20
          echo "Nginx logs:"
          docker logs neon-nginx --tail 20