# name: Deploy to VPS

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
    
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4
      
#     - name: Deploy to VPS
#       uses: appleboy/ssh-action@v1.0.3
#       with:
#         host: ${{ secrets.VPS_HOST }}
#         username: ${{ secrets.VPS_USERNAME }}
#         password: ${{ secrets.VPS_PASSWORD }}
#         script: |
#           # Masuk ke direktori project
#           cd skirpsi-ippat
          
#           # Pull latest changes
#           git pull origin main
          
#           # Stop existing containers
#           # docker compose down
          
#           # Remove old images (optional, untuk menghemat space)
          
#           # Build and start containers
#           # docker compose up -d
          
#           docker stop frontend-ippat backend-ippat || true
#           docker rm frontend-ippat backend-ippat || true
      
#           docker image prune -f
          
#           # Rebuild hanya frontend & backend (tanpa mysql)
#           docker compose up -d

#           # Show running containers
#           docker ps
          
#           # Show logs untuk debugging jika diperlukan
#           echo "Deployment completed!"
#           echo "Backend logs:"
#           docker logs backend-ippat --tail 20
#           echo "Frontend logs:"
#           docker logs frontend-ippat --tail 20